// Generated by CoffeeScript 1.3.3

$(function() {
  var StartDate, day_str, diff, i, index_today, j, singer_name, songs_name, status, _i, _j;
  StartDate = new Date(2012, 9, 5);
  diff = parseInt((new Date().getTime() / 1000 - StartDate.getTime() / 1000) / (60 * 60 * 24));
  index_today = diff % 4 !== 2 ? diff % 4 : 0;
  day_str = ['miku', 'gumi', '_miku', 'luka'];
  singer_name = {
    'miku': '初音ミク',
    'gumi': 'GUMI',
    '_miku': '_初音ミク',
    'luka': '巡音ルカ'
  };
  songs_name = [["夕焼け小焼け", "ロンドン橋落ちた", "シャボン玉"], ["きらきら星", "どんぐりころころ", "さくら"], ["_"], ["あめふり", "ひなまつり", "荒城の月"]];
  status = ['before', 'after'];
  for (i = _i = 0; _i <= 2; i = ++_i) {
    $('</p>').append("音源: VOCALOID&trade;2 " + singer_name[day_str[index_today]]).prependTo(".service_demo:eq(" + i + ")");
    $('</p>').append("曲名: " + songs_name[index_today][i]).prependTo(".service_demo:eq(" + i + ")");
    for (j = _j = 0; _j <= 1; j = ++_j) {
      $('.service_text').eq(i * 2 + j).after("<audio class='service_audio' controls><source src='audio/" + day_str[index_today] + i + "_" + status[j] + ".ogg' type='audio/ogg'><source src='audio/" + day_str[index_today] + i + "_" + status[j] + ".mp3' type='audio/mpeg'></audio>");
    }
  }
});
